# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4be9609b466e049e26986c6bf96bcd59355ba3e076dd46f577c53d0c10ad6c1be386b36540b093fe16b38eff222af672cc66426da67afbd254784431daf7382

test:
  secret_key_base: 7aeb827ed39852f105aff4060f92ead916d16966f7b3a02174e5827c960b4d469ee1d68f7181235c686cb98a9ed15ddc010c1e7f07dc2e653f7c9f384a92cb7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
